name: DS_HCA

channels:
  - defaults

dependencies:
  - python>=3.6
  - ipython
  - anaconda
  - numpy
  - pandas>=0.19.0
  - scipy
  - seaborn>=0.8.1
  - scikit-learn>=0.19.1
  - pip>=18.0
  - pip:
    - tqdm
    - tables
